### ISSUE TITLE
Do not package the .yarn-cache dir (reduce the unpacked size 322 times)

### ISSUE THREAD

**Issue by ChALkeR** [university-of-ant-solutions/feathers-fetch-service#2]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Atm, your npm package `feathers-fetch-service@1.0.0-beta.2` has packaged size **18.8 MiB**, and installed size **57.83 MiB**.

**57.65 MiB** (99.69%) of that is consumed by the `.yarn-cache` directory.

I suspect that that directory was accidently packaged.

You could add it to `.npmignore` (if you have an `.npmignore` already) or to `.gitignore` (if you don't have an `.npmignore`).

---

Your current package files (as of `feathers-fetch-service@1.0.0-beta.2`):

```
feathers-fetch-service-1.0.0-beta.2.tgz/
├── AUTHORS
├── bin
│   ├── constant
│   ├── help
│   ├── scripts
│   │   ├── exec
│   │   ├── exec.help
│   │   ├── exec.usage
│   │   ├── .help
│   │   ├── .logo
│   │   ├── logs
│   │   ├── logs.help
│   │   ├── logs.usage
│   │   ├── start
│   │   ├── start.help
│   │   ├── start.usage
│   │   ├── state
│   │   ├── state.help
│   │   ├── state.usage
│   │   ├── stop
│   │   ├── stop.help
│   │   └── stop.usage
│   ├── snail
│   └── utils
│       └── utils
├── build
│   ├── Base.js
│   └── index.js
├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── docker-compose.yml
├── Dockerfile
├── .dockerignore
├── .eslintignore
├── .eslintrc
├── .gitlab
│   ├── issue_templates
│   │   ├── Bug.md
│   │   └── Feature Proposal.md
│   └── merge_request_templates
│       └── Pull Request.md
├── .gitlab-ci.yml
├── lib
│   ├── Base.js
│   └── index.js
├── LICENSE.md
├── nodemon.json
├── .npmignore
├── package.json
├── README.md
├── .yarn-cache
│   └── v1
│       ...
└── yarn.lock

1302 directories, 11166 files
```

**Comment by particle4dev** [comment]
@ChALkeR thanks for letting me know. I noticed that too.
This issue has been resolved in this commit:

https://github.com/university-of-ant-solutions/feathers-fetch-service/commit/d7fd356c78cd924db6b1110e39672a96754e4b9d
